### ISSUE TITLE
Generate Demo Data menu

### ISSUE THREAD

**Issue by opitux** [bdeshayes/Kanboard-plugin-DemoData#1]
Thank you for this interesting plugin :)
Maybe I'm looking in the wrong place but I have no "Generate Demo Data" menu in Kanboard settings :/ 
I use Kanboard 1.2.2

By the way, you should correct "Create the **Wunderlist** folder" in the readme.md file ;)

**Comment by bdeshayes** [comment]
## Installation
  1. Navigate to the `plugins` directory, located in the root installation directory of Kanboard
  2. Create the `DemoData` folder
  3. Download the latest release [here](https://github.com/bdeshayes/Kanboard-plugin-DemoData/releases/tag/v1.0.0)
  4. Extract all files in the directory contained in the archive file you downloaded in the `DemoData` directory created previously

## Usage
Trash the db.sqlite database in the data directory.
Login as admin / admin. Click on the far right pull down menu and choose Settings.
At the bottom of the leftside list click Generate Demo Data

**Comment by opitux** [comment]
:/
I still don't have the "Generate Demo Data" menu in Kanboard settings.
Ubuntu 16.04, Kanboard 1.2.2 on http://localhost/kanboard/

**Comment by bdeshayes** [comment]
Is the plugin installed?
ie Is it showing in the list of installed plugins?

Also I think the menu "Generate Demo Data" only shows up for the admin user.

**Comment by opitux** [comment]
Yes, it is installed and visible in the list of installed plugins.
And I'm admin of course. 
I'll try to look into more detail when I have some time.
